name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Ejecuta diariamente a medianoche
  workflow_dispatch: # Permite ejecutar manualmente el workflow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Platane/snk@v3.1.0
        with:
          github_user_name: ImTommyDev

      - name: Push Snake Animation to GitHub
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: output
          force: true
          file: dist/github-snake.svg
